name: DaSell
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  gap: any
  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.6
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  image_picker: ^0.8.4+7
  path_provider: ^2.0.9
  path: ^1.8.0
  location: ^4.3.0
  geolocator: ^8.1.1
  multi_image_picker2: ^5.0.2
  firebase_storage: ^10.2.6
  carousel_slider: ^4.0.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.2.3
  intl: ^0.17.0
  theme_provider: ^0.5.0
  shared_preferences: ^2.0.13
  firebase_messaging: ^11.2.6
  get_it: ^7.2.0
  firebase_core: ^1.12.0
  http: ^0.13.4
  google_maps_flutter: ^2.1.2
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^9.2.0
  pull_to_refresh: ^2.0.0
  google_fonts: ^2.3.1
  animate_do: ^2.1.0
  bloc: ^8.0.3
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  google_polyline_algorithm: ^3.1.0
  permission_handler: ^8.3.0
  emoji_picker_flutter: ^1.0.8
  fluttertoast: ^8.0.9
  grouped_list: ^4.1.0
  auto_size_text: ^3.0.0
  geocoder2: ^1.1.0
  lottie: ^1.2.2
  image_cropper: ^1.4.1
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
  flutter_app_badger: ^1.3.0
  flutter_local_notifications: ^9.2.0
  timeago: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/10-2mano.png"
    adaptive_icon_background: "assets/icon/icon-app.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/chat_back.png
      - assets/images/boy.svg
      - assets/json/categories.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Billabong
        fonts:
          - asset: assets/fonts/Billabong.ttf
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
      - family: Roboto
        fonts:
            - asset: assets/fonts/Roboto-Regular.ttf
              weight: 400
            - asset: assets/fonts/Roboto-Medium.ttf
              weight: 500
            - asset: assets/fonts/Roboto-Bold.ttf
              weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
